data:
  tokenizer: null
  chat_template: null  # override in code
  train_files: examples/data_preprocess/gsm8k_test/train_gsm8k.parquet #train.parquet 
  val_files: [examples/data_preprocess/gsm8k_test/test_gsm8k.parquet] #[aime2024.parquet, math500.parquet] 
  prompt_key: prompt #question
  max_prompt_length: 1024
  max_response_length: 7168
  train_batch_size: 8 #64
  val_batch_size: null # DEPRECATED: Validation datasets are sent to inference engines as a whole batch, which will schedule the memory themselves
  return_raw_input_ids: False  # This should be set to true when the tokenizer between policy and rm differs
  return_raw_chat: True #必须把原始的 prompt（也就是“raw chat”）拿过来
  shuffle: True


actor_rollout_ref:
  #phi: ${phi} # inherit phi config
  hybrid_engine: True
  model:
    path: Qwen/Qwen2.5-7B
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: True
  actor:
    strategy: fsdp  # This is for backward-compatibility
    ppo_mini_batch_size: 8 #64  # per GPU
    ppo_micro_batch_size: null # will be deprecated, use ppo_micro_batch_size_per_gpu
    ppo_micro_batch_size_per_gpu: 1
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 16384 # n * ${data.max_prompt_length} + ${data.max_response_length}
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.0
    use_kl_loss: False # True for GRPO
    kl_loss_coef: 0.001 # for grpo
    kl_loss_type: low_var_kl # for grpo
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1 # sp size
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
      min_lr_ratio: null   # only useful for warmup with cosine
      warmup_style: constant  # select from constant/cosine
      total_training_steps: -1  # must be override by program
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
  ref:
    fsdp_config:
      param_offload: False
      fsdp_size: -1
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: 2
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: 1  # ${actor_rollout_ref.actor.ulysses_sequence_parallel_size}
  rollout:
    name: vllm # or hf
    temperature: 1.0
    top_k: -1 #-1 # 0 for hf rollout, -1 for vllm rollout
    top_p: 1
    use_fire_sampling: False # https://arxiv.org/abs/2410.21236
    prompt_length: ${data.max_prompt_length}  # not use for opensource
    response_length: ${data.max_response_length}
    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    gpu_memory_utilization: 0.9
    ignore_eos: False
    enforce_eager: False
    free_cache_engine: False
    load_format: dummy_dtensor
    tensor_model_parallel_size: 1
    max_num_batched_tokens: null
    max_model_len: 512 #8192
    max_num_seqs: 256 #2048
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: ${actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu}
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    disable_log_stats: True
    enable_chunked_prefill: True # may get higher throughput when set to True. When activated, Please increase max_num_batched_tokens or decrease max_model_len.
    # for hf rollout
    do_sample: True
    n: 2 # rollout number
    # Phi-Decoding 参数
    step_beam_size: 2
    num_foresight: 8
    num_rollout: 2
    width_pruning_strategy: low_sigma
    depth_pruning_strategy: cluster
    cluster_num: 2
    threshold: 0.7
    least_foresight_num: 4
    sigma_rate: 1.0
    seed: 42

critic:
  strategy: fsdp
  optim:
    lr: 5e-6
    lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
    min_lr_ratio: null   # only useful for warmup with cosine
    warmup_style: constant  # select from constant/cosine
    total_training_steps: -1  # must be override by program
  model:
    path: ${actor_rollout_ref.model.path}
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: True
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      fsdp_size: -1
  ppo_mini_batch_size: 8 #128
  ppo_micro_batch_size: null # will be deprecated, use ppo_micro_batch_size_per_gpu
  ppo_micro_batch_size_per_gpu: 2
  forward_micro_batch_size: ${critic.ppo_micro_batch_size}
  forward_micro_batch_size_per_gpu: ${critic.ppo_micro_batch_size_per_gpu}
  use_dynamic_bsz: True
  ppo_max_token_len_per_gpu: 24000  # (${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}) * 2
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: 1 # sp size
  ppo_epochs: 1
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5

reward_model:
  enable: True # True to enable reward model
  type: prm
  credit_assignment: 0.1  # ['gamma-decay', 'strict min-form', float (>0, means temperature in approx. min-form)]
  training: False
  strategy: fsdp
  optim:
    lr: 5e-6
    lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
    min_lr_ratio: null   # only useful for warmup with cosine
    warmup_style: constant  # select from constant/cosine
    total_training_steps: -1  # must be override by program
  model:
    path: jinachris/PURE-PRM-7B
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: True
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
  micro_batch_size: null
  micro_batch_size_per_gpu: 2
  ulysses_sequence_parallel_size: 1
  use_dynamic_bsz: True
  forward_max_token_len_per_gpu: 24000
  reward_manager: prime
  verifiable_reward_coef: 1.0
  modeling_reward_coef: 0.5
  repeatness_punishment: False
  high_repeat_threshold: 0.2

curriculum_learning:
  enable: True
  fn_name: remove_extreme
  fn_params:
    lower_percentile_bound: 25
    upper_percentile_bound: 75

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: rloo
  adv_norm: True
  kl_penalty: low_var_kl  # how to estimate kl divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

trainer:
  val_before_train: false   # 取消训练前的初始验证
  debug_mode: False
  total_epochs: 20
  total_training_steps: null
  project_name: pure_verl
  experiment_name: Qwen2p5-7B_prompts-${data.train_batch_size}_n-${actor_rollout_ref.rollout.n}
  logger: ['console', 'wandb']
  val_generations_to_log_to_wandb: 0
  nnodes: 1
  n_gpus_per_node: 4 #from 8 change to 4
  save_freq: 50
  # auto: find the last ckpt to resume. If can't find, start from scratch
  resume_mode: auto # or auto or resume_path if 
  resume_from_path: null
  test_freq: 0 #10 不验证
  critic_warmup: 0
  default_hdfs_dir: null
  remove_previous_ckpt_in_save: False
  del_local_ckpt_after_load: False
  default_local_dir: logs/${trainer.project_name}/${trainer.experiment_name}
